# Generated by Django 3.1.7 on 2021-02-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptocurrencyFromBithumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_currency', models.CharField(blank=True, max_length=50, null=True)),
                ('order_currency', models.CharField(blank=True, max_length=50, null=True)),
                ('bids_asks', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('time_fromapi', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'cryptocurrency_from_bithumb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialProductsFromKrx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=50, null=True)),
                ('ticker', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('count_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('time_fromapi', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'financial_products_from_krx',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, max_length=50, null=True)),
                ('count_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'miscellaneous',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoneyExchangeFromKoreaexim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(blank=True, db_column='RESULT', null=True)),
                ('cur_unit', models.CharField(blank=True, db_column='CUR_UNIT', max_length=50, null=True)),
                ('cur_nm', models.CharField(blank=True, db_column='CUR_NM', max_length=50, null=True)),
                ('ttb', models.CharField(blank=True, db_column='TTB', max_length=50, null=True)),
                ('tts', models.CharField(blank=True, db_column='TTS', max_length=50, null=True)),
                ('deal_bas_r', models.CharField(blank=True, db_column='DEAL_BAS_R', max_length=50, null=True)),
                ('bkpr', models.CharField(blank=True, db_column='BKPR', max_length=50, null=True)),
                ('yy_efee_r', models.CharField(blank=True, db_column='YY_EFEE_R', max_length=50, null=True)),
                ('ten_dd_efee_r', models.CharField(blank=True, db_column='TEN_DD_EFEE_R', max_length=50, null=True)),
                ('kftc_deal_bas_r', models.CharField(blank=True, db_column='KFTC_DEAL_BAS_R', max_length=50, null=True)),
                ('kftc_bkpr', models.CharField(blank=True, db_column='KFTC_BKPR', max_length=50, null=True)),
                ('update_time', models.DateTimeField()),
                ('time_fromapi', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'money_exchange_from_koreaexim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NormalizationUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, max_length=50, null=True)),
                ('count_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('price_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('fromurl', models.CharField(blank=True, max_length=50, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'normalization_unit',
                'managed': False,
            },
        ),
    ]
